### ISSUE TITLE
Crash with version 6.14.00

### ISSUE THREAD

**Issue by GREIKA** [GregTech6-Unofficial/GregTech6-Unofficial#7]
here's the crash report: https://ghostbin.co/paste/23zsc/raw
It worked fine with 6.13.01. Here's my mod list: https://ghostbin.co/paste/hfe8q/raw

**Comment by Drymouthman** [comment]
I'm having the same issues as you, more or less. Looking through my fml-client logs, every crash is related to the fluid registry, such as
`[Client thread/ERROR] [FML/]: The fluid registry is corrupted. A fluid gregapi.fluid.FluidGT lubricant is not properly registered. The mod that registered this is broken`
and
`[Client thread/ERROR] [FML/]: The fluid registry is corrupted. A fluid gregapi.fluid.FluidGT kerosine is not properly registered. The mod that registered this is broken`
Since version 6.14 also merges greg's official changes into it, I'm gonna guess something broke in the proccess.

**Comment by yuesha-yc** [comment]
Already taking look on it.

**Comment by yuesha-yc** [comment]
Fixed in 6.14.01

**Comment by Drymouthman** [comment]
Can confirm, works for me.

**Comment by GREIKA** [comment]
It also works for me now.
